version: "3"
services:
  historian:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
  historian-db:
    image: postgres
    environment:
      - POSTGRES_DB=historian
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@historian-db:5432/historian
    ports:
      - "5432:5432"
    volumes:
      - historian-db-volume:/var/lib/postgresql/data

volumes:
  historian-db-volume:
    driver: local
