db:
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5432
  name: "historian"
  driver: "@format postgresql+psycopg2://{this.db.user}:{this.db.password}@{this.db.host}:{this.db.port}/{this.db.name}"
